In [18]:
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, classification_report
from keras.models import Sequential
from keras.layers import Dense

data = genfromtxt("../Datasets/Bank Notes/bank_note_data.txt", delimiter=",")
print(data)

[[  3.6216    8.6661   -2.8073   -0.44699   0.     ]
 [  4.5459    8.1674   -2.4586   -1.4621    0.     ]
 [  3.866    -2.6383    1.9242    0.10645   0.     ]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771    1.     ]
 [ -3.5637   -8.3827   12.393    -1.2823    1.     ]
 [ -2.5419   -0.65804   2.6842    1.1952    1.     ]]


In [11]:
#The labels are the last column of the matrix.

labels = data[:, 4]
print("labels: ", labels)

#Features are all the columns excluding the last one
features = data[:,0:4]
print("\nfeatures:\n", features)

X = features
y = labels

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print("\n", X_train, "\n", "\nlen(X_train): ", len(X_train))

print("\n", X_test, "\n", "\nlen(X_test): ", len(X_test))

print("\n", y_train, "\n", "\nlen(X_test): ", len(y_train))

print("\n", y_test, "\n", "\nlen(y_test): ", len(y_test))

labels:  [0. 0. 0. ... 1. 1. 1.]

features:
 [[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]

 [[-0.8734   -0.033118 -0.20165   0.55774 ]
 [ 2.0177    1.7982   -2.9581    0.2099  ]
 [-0.36038   4.1158    3.1143   -0.37199 ]
 ...
 [-7.0364    9.2931    0.16594  -4.5396  ]
 [-3.4605    2.6901    0.16165  -1.0224  ]
 [-3.3582   -7.2404   11.4419   -0.57113 ]] 
 
len(X_train):  919

 [[ 1.5691    6.3465   -0.1828   -2.4099  ]
 [-0.27802   8.1881   -3.1338   -2.5276  ]
 [ 0.051979  7.0521   -2.0541   -3.1508  ]
 ...
 [ 3.5127    2.9073    1.0579    0.40774 ]
 [ 5.504    10.3671   -4.413    -4.0211  ]
 [-0.2062    9.2207   -3.7044   -6.8103  ]] 
 
len(X_test):  453

 [1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1.
 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0

In [8]:
scaler_object = MinMaxScaler()

scaler_object.fit(X_train)

scaled_X_train = scaler_object.transform(X_train)

scaled_X_test = scaler_object.transform(X_test)

print(scaled_X_train.max())

print(scaled_X_train.min())

model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(scaled_X_train, y_train, epochs=50, verbose=2)


1.0000000000000002
0.0
Epoch 1/50
29/29 - 1s - loss: 0.6790 - accuracy: 0.5495 - 751ms/epoch - 26ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6732 - accuracy: 0.5495 - 40ms/epoch - 1ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6675 - accuracy: 0.5495 - 41ms/epoch - 1ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6624 - accuracy: 0.5495 - 42ms/epoch - 1ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6581 - accuracy: 0.5495 - 41ms/epoch - 1ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6532 - accuracy: 0.5495 - 39ms/epoch - 1ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6474 - accuracy: 0.5495 - 43ms/epoch - 1ms/step
Epoch 8/50
29/29 - 0s - loss: 0.6402 - accuracy: 0.5713 - 40ms/epoch - 1ms/step
Epoch 9/50
29/29 - 0s - loss: 0.6312 - accuracy: 0.6181 - 39ms/epoch - 1ms/step
Epoch 10/50
29/29 - 0s - loss: 0.6214 - accuracy: 0.6768 - 42ms/epoch - 1ms/step
Epoch 11/50
29/29 - 0s - loss: 0.6105 - accuracy: 0.6921 - 40ms/epoch - 1ms/step
Epoch 12/50
29/29 - 0s - loss: 0.5983 - accuracy: 0.6931 - 41ms/epoch - 1ms/step
Epoch 13/50


In [20]:
print(model.metrics_names)

predictions = model.predict_classes(scaled_X_test)

confusion_matrix(y_test, predictions)

print(classification_report(y_test, predictions))

[]
15/15 [==============================] - 0s 2ms/step


ValueError: Classification metrics can't handle a mix of binary and multilabel-indicator targets

In [23]:
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix, classification_report

# Load data from the file
data = genfromtxt("../Datasets/Bank Notes/bank_note_data.txt", delimiter=",")
print(data)

# The labels are the last column of the matrix.
labels = data[:, 4]
print("labels: ", labels)

# Features are all the columns excluding the last one
features = data[:, 0:4]
print("\nfeatures:\n", features)

X = features
y = labels

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print("\n", X_train, "\n", "\nlen(X_train): ", len(X_train))

print("\n", X_test, "\n", "\nlen(X_test): ", len(X_test))

print("\n", y_train, "\n", "\nlen(y_train): ", len(y_train))

print("\n", y_test, "\n", "\nlen(y_test): ", len(y_test))

scaler_object = MinMaxScaler()

scaler_object.fit(X_train)

scaled_X_train = scaler_object.transform(X_train)

scaled_X_test = scaler_object.transform(X_test)

print(scaled_X_train.max())

print(scaled_X_train.min())

model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

print(model.metrics_names)

predictions = model.predict(scaled_X_test)
predictions_classes = (predictions > 0.5).astype(int)

conf_matrix = confusion_matrix(y_test, predictions_classes)
print(conf_matrix)

class_report = classification_report(y_test, predictions_classes)
print(class_report)


[[  3.6216    8.6661   -2.8073   -0.44699   0.     ]
 [  4.5459    8.1674   -2.4586   -1.4621    0.     ]
 [  3.866    -2.6383    1.9242    0.10645   0.     ]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771    1.     ]
 [ -3.5637   -8.3827   12.393    -1.2823    1.     ]
 [ -2.5419   -0.65804   2.6842    1.1952    1.     ]]
labels:  [0. 0. 0. ... 1. 1. 1.]

features:
 [[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]

 [[-0.8734   -0.033118 -0.20165   0.55774 ]
 [ 2.0177    1.7982   -2.9581    0.2099  ]
 [-0.36038   4.1158    3.1143   -0.37199 ]
 ...
 [-7.0364    9.2931    0.16594  -4.5396  ]
 [-3.4605    2.6901    0.16165  -1.0224  ]
 [-3.3582   -7.2404   11.4419   -0.57113 ]] 
 
len(X_train):  919

 [[ 1.5691    6.3465   -0.1828   -2.4099  ]
 [-0.27802   8.1881   -3.1338   -2

Epoch 35/50
29/29 - 0s - loss: 0.2421 - accuracy: 0.9358 - 43ms/epoch - 1ms/step
Epoch 36/50
29/29 - 0s - loss: 0.2349 - accuracy: 0.9380 - 41ms/epoch - 1ms/step
Epoch 37/50
29/29 - 0s - loss: 0.2287 - accuracy: 0.9391 - 40ms/epoch - 1ms/step
Epoch 38/50
29/29 - 0s - loss: 0.2214 - accuracy: 0.9434 - 41ms/epoch - 1ms/step
Epoch 39/50
29/29 - 0s - loss: 0.2153 - accuracy: 0.9434 - 41ms/epoch - 1ms/step
Epoch 40/50
29/29 - 0s - loss: 0.2096 - accuracy: 0.9445 - 42ms/epoch - 1ms/step
Epoch 41/50
29/29 - 0s - loss: 0.2033 - accuracy: 0.9467 - 39ms/epoch - 1ms/step
Epoch 42/50
29/29 - 0s - loss: 0.1975 - accuracy: 0.9445 - 40ms/epoch - 1ms/step
Epoch 43/50
29/29 - 0s - loss: 0.1924 - accuracy: 0.9478 - 38ms/epoch - 1ms/step
Epoch 44/50
29/29 - 0s - loss: 0.1879 - accuracy: 0.9423 - 39ms/epoch - 1ms/step
Epoch 45/50
29/29 - 0s - loss: 0.1816 - accuracy: 0.9478 - 44ms/epoch - 2ms/step
Epoch 46/50
29/29 - 0s - loss: 0.1765 - accuracy: 0.9478 - 42ms/epoch - 1ms/step
Epoch 47/50
29/29 - 0s - los